services:
  postgres:
    build: 
      context: ./
      dockerfile: ./postgres/Dockerfile
      args:
        - POSTGRES_TAG=${POSTGRES_TAG}
        - LOAD_LANGUAGE
    tty: true
    volumes:
      - pg-data:${PGDATA}
      - ./postgres/entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - PGDATA
      - DB_USER
      - DB_TEMPLATE
      - UNACCENT_TEMPLATE
      - PGADMING_DB_NAME
      - PGADMING_DB_USER
      - PGADMIN_DB_PASSWORD
    networks:
      - internal
    profiles: [$POSTGRES_PROFILES]
volumes:
  pg-data:

networks:
  internal:
    driver: bridge