CREATE USER odoo12 WITH CREATEDB ENCRYPTED PASSWORD 'odoo12';
-- CREATE DATABASE odoo12;
-- GRANT ALL PRIVILEGES ON DATABASE postgres TO odoo12;

CREATE USER odoo13 WITH CREATEDB ENCRYPTED PASSWORD 'odoo13';

CREATE USER odoo14 WITH CREATEDB ENCRYPTED PASSWORD 'odoo14';

CREATE USER odoo15 WITH CREATEDB ENCRYPTED PASSWORD 'odoo15';

CREATE USER odoo16 WITH CREATEDB ENCRYPTED PASSWORD 'odoo16';

CREATE USER odoo17 WITH CREATEDB ENCRYPTED PASSWORD 'odoo17';

CREATE USER odoo18 WITH CREATEDB ENCRYPTED PASSWORD 'odoo18';

CREATE USER odoo19 WITH CREATEDB ENCRYPTED PASSWORD 'odoo19';

CREATE USER odoo20 WITH CREATEDB ENCRYPTED PASSWORD 'odoo20';